name: Power BI CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Requests
      run: pip install requests

    - name: Deploy to Power BI
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.PBI_CLIENT_SECRET }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
        WORKSPACE_ID: ${{ secrets.PBI_WORKSPACE_ID }}
      run: |
        python <<EOF
        import requests
        import os

        # Read env variables
        CLIENT_ID = os.environ["CLIENT_ID"]
        CLIENT_SECRET = os.environ["CLIENT_SECRET"]
        TENANT_ID = os.environ["TENANT_ID"]
        WORKSPACE_ID = os.environ["WORKSPACE_ID"]

        # Step 1: Get Token
        token_url = f"https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/token"

        payload = {
            'grant_type': 'client_credentials',
            'client_id': CLIENT_ID,
            'client_secret': CLIENT_SECRET,
            'scope': 'https://analysis.windows.net/powerbi/api/.default'
        }

        token_response = requests.post(token_url, data=payload)
        print("Token Status:", token_response.status_code)

        access_token = token_response.json().get("access_token")

        if not access_token:
            print("❌ Token not generated")
            print(token_response.text)
            exit(1)

        # Step 2: Upload PBIX
        file_path = "Samplecopy.pbix"

        url = f"https://api.powerbi.com/v1.0/myorg/groups/{WORKSPACE_ID}/imports?datasetDisplayName=Sample&nameConflict=CreateOrOverwrite"

        headers = {
            "Authorization": f"Bearer {access_token}"
        }

        files = {
            'file': ('Samplecopy.pbix', open(file_path, 'rb'), 'application/octet-stream')
        }

        response = requests.post(url, headers=headers, files=files)

        print("Upload Status:", response.status_code)
        print("Upload Response:", response.text)

        if response.status_code not in [200, 202]:
            print("❌ Upload failed")
            exit(1)
        else:
            print("✅ Upload successful")

        EOF
